webshop/account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("register/", views.register, name="register"),
    path("profile/", views.user_profile, name="user_profile"),
    path("profile/edit", views.user_profile_edit, name="user_profile_edit"),
]

webshop/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

webshop/shop/api/urls.py
from django.urls import path
from shop.api.views import (
    ProductListView,
    OrderListView,
)
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter(trailing_slash=False)
router.register(r"products", ProductListView, basename="product_list")
router.register(r"orders", OrderListView, basename="order_list")

app_name = "shop"

urlpatterns = [
    # path("products/", ProductListView, name="product_list"),
    # path("products/<pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    # path("orders/", OrderListView, name="order_list"),
    # path("orders/<pk>/", views.OrderDetailView.as_view(), name="order_detail"),
    url(r"^v1/", include(router.urls)),
]

webshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("termekek/", views.product_list, name="product_list"),
    path("sale/", views.on_sale_view, name="on_sale_view"),
    path("contact/", views.contact_view, name="contact"),
    path("about/", views.about_view, name="about"),
    path("kereses/", views.product_search, name="product_search"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

webshop/webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("account/", include("account.urls", namespace="account")),
    path("coupons/", include("coupons.urls", namespace="apply")),
    path("api/", include("shop.api.urls", namespace="api")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("", include("shop.urls", namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="product/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    on_sale = models.BooleanField(default=False)
    on_sale_price = models.IntegerField(blank=True)
    weight = models.IntegerField()
    units = models.IntegerField()
    daily_dose = models.IntegerField()
    ogyei_number = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)
        index_together = (("id", "slug"),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])


class ProductDescription(models.Model):
    product = models.ForeignKey(
        Product, related_name="product_description", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=250, blank=True)
    description = models.TextField(blank=True)


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, related_name="product_image", on_delete=models.CASCADE
    )
    image = models.ImageField()

webshop/shop/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "id": "searchfield",
                "class": "form-control mr-sm-2",
                "placeholder": "Keresés...",
            }
        ),
        label=False,
    )

webshop/shop/api/views.py
from rest_framework import generics, viewsets, filters, mixins
from shop.models import Product
from orders.models import Order, OrderItem
from shop.api.serializers import ProductSerializer, OrderSerializer, OrderItemSerializer
from rest_framework.permissions import IsAdminUser
from rest_framework.authentication import BasicAuthentication


class ProductListView(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet
):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAdminUser,)
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class OrderListView(
    mixins.RetrieveModelMixin, mixins.ListModelMixin, viewsets.GenericViewSet
):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAdminUser,)
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

webshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Product, ProductDescription, ProductImage
from cart.forms import CartAddProductForm
from .recommender import Recommender
from .forms import SearchForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    object_list = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)

    cart_product_form = CartAddProductForm()

    form = SearchForm()
    query = None
    results = []

    paginator = Paginator(object_list, 2)  # 3 posts in each page
    page = request.GET.get("page")

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if "query" in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data["query"]
            results = Product.objects.annotate(
                search=SearchVector("name", "description"),
            ).filter(search=query)
        return render(
            request,
            "shop/kereses.html",
            {
                "cart_product_form": cart_product_form,
                "categories": categories,
                "form": form,
                "query": query,
                "results": results,
            },
        )

    return render(
        request,
        "shop/product/list.html",
        {
            "category": category,
            "categories": categories,
            "page": page,
            "products": products,
            "cart_product_form": cart_product_form,
            "form": form,
            "query": query,
        },
    )


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    categories = Category.objects.all()
    descriptors = ProductDescription.objects.filter(
        product_id__in=Product.objects.filter(id=id)
    )
    images = ProductImage.objects.filter(product_id__in=Product.objects.filter(id=id))

    on_sale_products = Product.objects.filter(on_sale=True).exclude(id=id)
    on_sale_products = on_sale_products[:4]

    cart_product_form = CartAddProductForm()

    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(
        request,
        "shop/product/detail.html",
        {
            "product": product,
            "categories": categories,
            "on_sale_products": on_sale_products,
            "cart_product_form": cart_product_form,
            "descriptors": descriptors,
            "images": images,
            "recommended_products": recommended_products,
        },
    )


def home_view(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(
        request,
        "shop/index.html",
        {"category": category, "categories": categories, "products": products},
    )


def on_sale_view(request):
    products = Product.objects.filter(on_sale=True)
    categories = Category.objects.all()

    cart_product_form = CartAddProductForm()

    return render(
        request,
        "shop/product/sale.html",
        {
            "products": products,
            "categories": categories,
            "cart_product_form": cart_product_form,
        },
    )


def contact_view(request):
    categories = Category.objects.all()

    return render(
        request,
        "shop/contact.html",
        {"categories": categories},
    )


def about_view(request):
    categories = Category.objects.all()

    return render(
        request,
        "shop/about.html",
        {"categories": categories},
    )


def product_search(request):
    form = SearchForm()
    query = None
    results = []

    categories = Category.objects.all()

    cart_product_form = CartAddProductForm()

    if "query" in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data["query"]
            results = Product.objects.annotate(
                search=SearchVector("name", "description"),
            ).filter(search=query)

    return render(
        request,
        "shop/kereses.html",
        {
            "cart_product_form": cart_product_form,
            "categories": categories,
            "form": form,
            "query": query,
            "results": results,
        },
    )

webshop/shop/templates/shop/about.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}

<div class="container mt-3 pt-3">
    <h1>Ide lehet tenni szemelyes bemutatkozast, profil fotokat, kis leirast a boltrol stb.....</h1>
</div>

{% endblock %}

webshop/shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Csaba Keller, www.csabakeller.com">
    <title>VitaKing · Budaörs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Fontawesome core -->
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <!-- Custom styles for this template -->
    <link href="{% static "css/carousel.css" %}" rel="stylesheet">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>

<body>
    <!--/ Nav Start /-->
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #2589FF;">
        <a class="navbar-brand" href="{% url "shop:home_view" %}"><img class="img-fluid"
                src="{% static 'img/vitaminkiraly-vitamin-webaruhaz.png' %}" alt="" /></a></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04"
            aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:home_view" %}">Főoldal <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Termékeink</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{% url "shop:product_list" %}">Összes</a>
                        {% for c in categories %}
                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        {% endfor %}
                        <a class="dropdown-item" href="{% url "shop:on_sale_view" %}" id="nav-on-sale">Akciós</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:about" %}">Rólunk</a>
                </li>
                <li class="nav-item mr-sm-2">
                    <a class="nav-link" href="{% url "shop:contact" %}">Kapcsolat</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:product_search" %}">Keresés</a>
                </li>
            </ul>
            <ul class="navbar-nav my-2 my-md-0 mr-md-3">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:user_profile" %}">Hello {{ user.first_name }}</a>
                </li>
                <li class="nav-item" id="cart">

                    {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                    <a href="{% url "cart:cart_detail" %}" class="nav-link">
                        <span class="badge badge-danger mr-1">{{ total_items }}</span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block">Kosár</span>
                    </a>
                    {% else %}
                    <a href="{% url "cart:cart_detail" %}" class="nav-link">
                        <span class="badge badge-light mr-1">0</span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block">Kosár</span>
                    </a>
                    {% endif %}
                    {% endwith %}

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:logout" %}">Kilépés</a>
                </li>
                {% else %}
                <li class="nav-item" id="cart">

                    {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                    <a href="{% url "cart:cart_detail" %}" class="nav-link">
                        <span class="badge badge-danger mr-1">{{ total_items }}</span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block">Kosár</span>
                    </a>
                    {% else %}
                    <a href="{% url "cart:cart_detail" %}" class="nav-link">
                        <span class="badge badge-light mr-1">0</span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block">Kosár</span>
                    </a>
                    {% endif %}
                    {% endwith %}

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:login" %}">Bejelentkezés</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>
    <!--/ Nav End /-->


    <!--/ Content Start /-->

    {% if messages %}
    {% for message in messages %}

    <div class="container mt-3 pt-2">
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>

    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <!--/ Content End /-->


    <!--/ Footer Start /-->
    <footer class="footer mt-auto py-3">
        <div class="row text-center padding">
            <div class="col-12">
                <img src="{% static 'img/vitaminkiraly-vitamin-webaruhaz.png' %}" alt="">
                <p><i class="fas fa-map-marker-alt"></i><strong> Vitaking - Budaörs Szabadság út 58.</strong></p>
                <a href="tel:+36308535626">+36 30 853 5626</a>
            </div>
            <div class="col-12 social padding">
                <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/vitakingbudaors"><i
                        class="fab fa-facebook"></i></a>
                <a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/vitaminkingbudaors/"><i
                        class="fab fa-instagram"></i></a>
                <h6>&copy; 2020 · csabakeller.com</h6>
            </div>
        </div>
    </footer>
    <!--/ Footer End /-->

    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>

    <script>
        $(window).on("load", function () {
            $(".loader-wrapper").fadeOut("slow");
        });

        $(function () {
            $('[data-toggle="popover"]').popover()
        })
    </script>
</body>

</html>

webshop/shop/templates/shop/contact.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}

<div class="container mt-3 pt-3">
    <div class="row">
        <div class="col">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10789.991626873245!2d18.956865!3d47.460726!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9b6588aef732828d!2sVitamin-%20%C3%A9s%20Biobolt%2C%20Vitaminkir%C3%A1ly%20Buda%C3%B6rs!5e0!3m2!1shu!2suk!4v1601497867569!5m2!1shu!2suk"
                width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
                tabindex="0"></iframe>
        </div>
        <div class="col">
            <h5>Nyitvatartás</h5>
            <p>Hétfő 10:00–19:00</p>
            <p>Kedd 10:00–19:00</p>
            <p>Szerda 10:00–19:00</p>
            <p>Csütörtök 10:00–19:00</p>
            <p>Péntek 10:00–19:00</p>
            <p>Szombat <i>Zárva</i></p>
            <p>Vasárnap <i>Zárva</i></p>
        </div>
    </div>
</div>

{% endblock %}

webshop/shop/templates/shop/kereses.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Keresés
{% endblock %}

{% block content %}

<div class="container-fluid mt-3 pt-2">
    <div class="loader-wrapper">
        <div class="d-flex justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                <h3>Termékkategóriák</h3>
                <ul class="nav flex-column">
                    <li {% if not category %} class="nav-item" {% endif %}>
                        <a class="nav-link active" href="{% url "shop:product_list" %}">Összes
                        </a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %} class="nav-item" {% endif %}>
                        <a class="nav-link active" href="{{ c.get_absolute_url }}">{{ c.name }}
                        </a>
                    </li>
                    {% endfor %}
                    <li {% if not category %} class="nav-item" {% endif %}>
                        <a class="nav-link active" href="{% url "shop:on_sale_view" %}" id="nav-on-sale">Akciós
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-auto mt-3">
            {% if query %}
            <div class="col-md-6">
                <form method="get">
                    <div class="input-group">
                        {{ form.query }}
                        <button type="submit" class="btn btn-outline-dark ml-2"><span><i class="fas fa-search"></i>
                                Keresés</span></button>
                    </div>
                </form>
            </div>

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1>Keresési eredmények: “{{ query }}”</h1>
                <h3>
                    {% with results.count as total_results %}
                    - Találatok száma: {{ total_results }}
                    {% endwith %}
                </h3>
            </div>

            <div class="row">
                <div class="col">
                    <div class="row">
                        {% for product in results %}
                        <div class="col-md-auto">
                            <div class="card" style="width: 18rem;">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}"
                                    class="card-img-top" alt="...">
                                {% if product.on_sale %}
                                <div class="top-right">Akció</div>
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title"><a
                                            href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </h5>
                                    {% if product.on_sale %}
                                    <p class="card-text"><del>{{ product.price|intcomma }} Ft.</del><span>
                                            {{ product.on_sale_price|intcomma }} Ft.</span></p>
                                    {% else %}
                                    <p class="card-text">{{ product.price|intcomma }} Ft.</p>
                                    {% endif %}
                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                        <div class="row">
                                            <div class="col-md-4 mt-2">
                                                <label
                                                    for="{{ cart_product_form.quantity.id_for_label }}">Mennyiség:</label>
                                            </div>
                                            <div class="form-group col-md-6 ml-3">
                                                {% csrf_token %}
                                                {{ cart_product_form.quantity.errors }}
                                                {{ cart_product_form.quantity }}
                                            </div>
                                        </div>
                                        <input type="submit" class="btn btn-primary btn-sm mt-3" value="Kosárba teszem">
                                        <a href="{{ product.get_absolute_url }}"
                                            class="btn btn-outline-info btn-sm mt-3 mr-2">Megtekint</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% else %}
            <h1>Keressen termékeink között</h1>

            <form method="get">
                <div class="input-group">
                    {{ form.query }}
                    <button type="submit" class="btn btn-outline-dark ml-2"><span><i class="fas fa-search"></i>
                            Keresés</span></button>
                </div>
            </form>

            {% endif %}

            <script>
                $(window).on("load", function () {
                    $(".loader-wrapper").fadeOut("slow");
                });
            </script>
        </main>
    </div>
</div>

{% endblock %}