webshop/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

webshop/coupons/urls.py
from django.urls import path
from . import views

app_name = "coupons"

urlpatterns = [path("apply/", views.coupon_apply, name="apply")]

webshop/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path(
        "admin/order/<int:order_id>/pdf/", views.admin_order_pdf, name="admin_order_pdf"
    ),
]

webshop/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("termekek/", views.product_list, name="product_list"),
    path("sale/", views.on_sale_view, name="on_sale_view"),
    path("contact/", views.contact_view, name="contact"),
    path("about/", views.about_view, name="about"),
    path("kereses/", views.product_search, name="product_search"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

webshop/webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("account/", include("account.urls", namespace="account")),
    path("coupons/", include("coupons.urls", namespace="apply")),
    path("api/", include("shop.api.urls", namespace="api")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("", include("shop.urls", namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "id": "addtocartform",
            }
        ),
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label="Mennyiség",
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )


class CartAddSingleProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "id": "exampleFormControlSelect1",
                "onchange": "this.form.submit()",
            }
        ),
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

webshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from shop.recommender import Recommender
from .cart import Cart
from .forms import CartAddProductForm, CartAddSingleProductForm
from coupons.forms import CouponApplyForm
from django.contrib import messages


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )
        messages.success(request, "Termék hozzáadva a kosárhoz!")
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.info(request, "Termék törölve a kosárból!")
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    for item in cart:
        item["update_quantity_form"] = CartAddSingleProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )

    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    if len(cart) != 0:
        cart_products = [item["product"] for item in cart]
        recommended_products = r.suggest_products_for(cart_products, max_results=4)
    else:
        recommended_products = 0

    return render(
        request,
        "cart/detail.html",
        {
            "categories": categories,
            "cart": cart,
            "coupon_apply_form": coupon_apply_form,
            "recommended_products": recommended_products,
        },
    )

webshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load humanize %}


{% block content %}
<div class="container mt-3 pt-2">
    <div class="row">
        <h1>Kosár tartalma:</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Termék</th>
                    <th scope="col">Mennyiség</th>
                    <th scope="col">Egységár</th>
                    <th scope="col">Ár</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    </td>
                    <td>
                        <div class="form-group">
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                {% csrf_token %}
                            </form>
                        </div>
                    </td>
                    {% if product.on_sale %}
                    <td><del>{{ product.price|intcomma }} </del>{{ product.on_sale_price|intcomma }} Ft.</td>
                    <td>{{ item.total_price_on_sale|intcomma }} Ft.</td>
                    {% else %}
                    <td>{{ product.price|intcomma }} Ft.</td>
                    <td>{{ item.total_price|intcomma }} Ft.</td>
                    {% endif %}
                    <td>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <button type="submit" class="btn btn-outline-danger">
                                <i class="fas fa-trash"></i>
                            </button>
                            {% csrf_token %}
                        </form>
                    </td>
                </tr>
                {% endwith %}
                {% empty %}
                <tr class="total">
                    <td colspan="5">Az Ön kosara üres!</td>
                </tr>
                {% endfor %}
                {% if cart.coupon %}
                <tr class="subtotal">
                    <td colspan="4">Részösszeg</td>
                    <td class="total-price">{{ cart.get_total_price|intcomma }} Ft.</td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4" class="text-success">
                        "{{ cart.coupon.code }}" kupon ({{ cart.coupon.discount }}%)
                    </td>
                    <td class="text-success">- {{ cart.get_discount|floatformat:0 }} Ft.</td>
                    <td></td>
                </tr>
                {% endif %}
                <tr class="total">
                    <td colspan="4">Végösszeg</td>
                    <td class="total-price">
                        {{ cart.get_total_price_after_discount|intcomma }} Ft.
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
    {% if cart.coupon %}
    <div class="row justify-content-between mt-3 pt-2">
        <div class="col-md-6">
            <p class="text-danger">*** Kuponok nem vonatkoznak a kedvezményes termékekre ***</p>
        </div>
        <div class="col-6 col-md-4">
            <a href="{% url "shop:product_list" %}" class="btn btn-primary">Vásárlás folytatása</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-secondary ml-2">Rendelés</a>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-between mt-3 pt-2">
        <div class="col-md-4">
            <form action="{% url "coupons:apply" %}" method="post">
                <div class="input-group">
                    {{ coupon_apply_form }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Beváltás</button>
                </div>
            </form>
        </div>
        <div class="col-6 col-md-4">
            <a href="{% url "shop:product_list" %}" class="btn btn-primary">Vásárlás folytatása</a>
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
            <a href="{% url "orders:order_create" %}" class="btn btn-secondary ml-2">Rendelés</a>
            {% else %}
            <button type="button" class="btn btn-secondary ml-2" data-toggle="popover" data-placement="right"
                title="Az Ön kosara üres!"
                data-content="Kérjük, adjon termékeket a kosárhoz a megrendelés folytatásához.">Rendelés</button>
            {% endif %}
            {% endwith %}
        </div>
    </div>
    {% endif %}

    {% if recommended_products %}
    <hr class="mt-3 pt-2">
    <h3 class="mt-3 pt-2"><strong>Érdekelhetnek még…</strong></h3>
    <div class="row mt-3 pt-2">
        {% for p in recommended_products %}
        <div class="col-md-auto mt-3">
            <div class="card" style="width: 18rem;">
                <img src="{% if p.image %}{{ p.image.url }}{% else %}{% endif %}" class="card-img-top" alt="...">
                {% if p.on_sale %}
                <div class="top-right">Akció</div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
                    </h5>
                    <!--<p class="card-text">{{ p.description|truncatewords:25|linebreaks }}</p>-->
                    {% if p.on_sale %}
                    <p class="card-text"><del>{{ p.price|intcomma }} Ft.</del><span>
                            {{ p.on_sale_price|intcomma }} Ft.</span></p>
                    {% else %}
                    <p class="card-text">{{ p.price|intcomma }} Ft.</p>
                    {% endif %}
                    <a href="{{ p.get_absolute_url }}" class="btn btn-info">Megtekint</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <hr class="mt-3 pt-2">

</div>
{% endblock %}